// Auto-generated by scripts/extract-images.py
const imageManifest = {
  "0afb5b75-9406-48fd-abd0-eb19dd1ace16": "jpg",
  "0f35b49f-0059-4a63-b281-0bcc2731d862": "jpg",
  "11677d19-5a3a-4700-b150-c134ac6a32a8": "jpg",
  "1c1d1d94-e455-42f8-ac6b-1fe4c74a9b3c": "jpg",
  "1d35663b-cf8e-471c-b3e1-6657e58d7d05": "jpg",
  "2a26f2f5-d981-4911-9d77-f75db92826f8": "jpg",
  "45154164-e820-4c56-bd68-3421e4850e3b": "jpg",
  "575d937b-40e8-4221-ba31-4831e235dcf5": "jpg",
  "8bf2961a-6fbb-4139-8f29-55815197405d": "png",
  "931dd399-a8bb-4c6f-a6e6-68d7c9a3eea0": "png",
  "9531646c-a4d9-486c-aa9a-aac2af073acd": "jpg",
  "a4c9cacf-f7c3-4d4a-b330-a9159c6168b7": "jpg",
  "ae4f24ce-fad0-4e9b-80b0-694233d81aca": "jpg",
  "b64ab3f5-d981-4561-9a69-b96aa9604813": "jpg",
  "b7dd19a7-8f89-48ea-adb8-a50b436e502a": "jpg",
  "daa51c47-be2b-45b5-9d8d-54c582dc7afe": "jpg",
  "e2f8d097-6671-4d63-ad56-99371088ae00": "jpg",
}

export default imageManifest
