#!/usr/bin/env python3
"""Extract images from bundled index.html.html (supports gzip-compressed manifest entries)."""
import base64
import gzip
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BUNDLE_CANDIDATES = [
    os.path.join(ROOT, "index.html.html"),
    os.path.join(ROOT, "_original_bundle.html"),
]

out_dir = os.path.join(ROOT, "public", "images")
os.makedirs(out_dir, exist_ok=True)

bundle_path = next((p for p in BUNDLE_CANDIDATES if os.path.isfile(p)), None)
if not bundle_path:
    print("No bundle file found", file=sys.stderr)
    sys.exit(1)

raw = open(bundle_path, "rb").read()
for enc in ("utf-16", "utf-8"):
    try:
        text = raw.decode(enc)
        if "__bundler/manifest" in text:
            break
    except UnicodeDecodeError:
        text = None
else:
    text = raw.decode("utf-8", errors="replace")

m = re.search(r'<script type="__bundler/manifest">(.*?)</script>', text, re.DOTALL)
if not m:
    print("Manifest not found", file=sys.stderr)
    sys.exit(1)

manifest = json.loads(m.group(1).strip())
manifest_out = {}

for uuid, entry in manifest.items():
    mime = entry.get("mime", "")
    if not mime.startswith("image/"):
        continue
    ext = mime.split("/")[1].replace("jpeg", "jpg")
    data = base64.b64decode(entry["data"])
    if entry.get("compressed"):
        data = gzip.decompress(data)
    path = os.path.join(out_dir, f"{uuid}.{ext}")
    with open(path, "wb") as f:
        f.write(data)
    manifest_out[uuid] = ext
    print(f"Saved: {uuid}.{ext} ({len(data)} bytes)")

# Write image manifest for React
js_path = os.path.join(ROOT, "src", "utils", "imageManifest.js")
lines = ["// Auto-generated by scripts/extract-images.py", "const imageManifest = {"]
for uuid, ext in sorted(manifest_out.items()):
    lines.append(f'  "{uuid}": "{ext}",')
lines.extend(["}", "", "export default imageManifest", ""])
open(js_path, "w", encoding="utf-8").write("\n".join(lines))
print(f"Wrote {js_path} ({len(manifest_out)} images)")
